name: Nx Affected Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push:
    if: ${{ github.event_name != 'pull_request' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 15, 16]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "master"

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build affected libraries
        run: npx nx affected --target=build --parallel --max-parallel=3

      - name: Run tests for affected libraries
        run: npx nx affected --target=test --parallel --max-parallel=2

  pr:
    if: ${{ github.event_name == 'pull_request' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 15, 16]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "master"

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build affected libraries
        run: npx nx affected --target=build --parallel --max-parallel=3

      - name: Run tests for affected libraries
        run: npx nx affected --target=test --parallel --max-parallel=2
